### ISSUE TITLE
Bug selected mandor pada Service Form

### ISSUE THREAD

**Issue by suryanto23** [Faayakhun/Final-Project-Frontend#19]
Setelah user mengisi Service Form, aplikasi akan mengarahkan user ke page list selected mandor untuk memilih mandor. Jika user tidak melewati tahap ini (back to previous page , quit , etc) maka Service Form akan tetap ter-POST ke model jasa pada database dengan mandor _null_

**Comment by Faayakhun** [comment]
sudah mas suryanto perbaiki ya
